name: E2E Tests

on: push

jobs:
  # Run E2E tests against specific WC and PHP versions
  e2e-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        wordpress:
          - '6.1.0'
        woocommerce:
          - '7.2.2' # TODO
        php:
          #          - '7.4'
          - '8.0'

    name: E2E Tests - WC ${{ matrix.woocommerce }} | WP ${{ matrix.wordpress }} | PHP ${{ matrix.php }}

    steps:
      - name: Checkout CopyCraft repository
        uses: actions/checkout@v2

      - name: Setup NodeJS and Cache Dependencies
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      # Install node dependencies if not present on cache
      - name: Install node dependencies
        run: npm ci

      - name: Kill process running on port 8084
        shell: bash
        run : |
          echo "::group::Kill webserver running on port 8084"
          sudo fuser -k -n tcp 8084
          echo "::endgroup::"

      - name: Prepare to Run E2E Tests
        run: TRAVIS_PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wordpress }} npm run docker:up

      - name: Run E2E Tests
        run: npm run test:e2e
