name: E2E Tests

on: push

jobs:
  # Run E2E tests against specific WC and PHP versions
  e2e-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        wordpress:
          - '6.1.0'
        woocommerce:
          - 'latest'
          # TODO: test against other WooCommerce versions by modifying wp-content/plugins/copycraft/tests/e2e/docker/initialize.sh
        php:
          - '7.4'
          - '8.0'

    name: E2E - WC ${{ matrix.woocommerce }} | WP ${{ matrix.wordpress }} | PHP ${{ matrix.php }}

    steps:
      - name: Checkout CopyCraft repository
        uses: actions/checkout@v2

      - name: Setup NodeJS and Cache Dependencies
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      # Install node dependencies if not present on cache
      - name: Install node dependencies
        run: npm ci

      - name: Kill process running on port 8084
        shell: bash
        run: |
          echo "::group::Kill webserver running on port 8084"
          sudo fuser -k -n tcp 8084
          echo "::endgroup::"

      - name: Prepare to Run E2E Tests
        run: PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wordpress }} WC_VERSION=${{ matrix.woocommerce }} npm run docker:up

      - name: Debug
        run: |
          env
          docker ps
          curl -v http://localhost:8084/
          curl -v http://localhost:8084/wp-admin/
          curl -v http://localhost:8084/?pagename=ready
          curl -v http://localhost:8084/wp-login.php
          curl -v http://localhost:8084/wp-content/plugins/woocommerce/readme.txt
          sleep 30
          curl -v http://localhost:8084/
          curl -v http://localhost:8084/wp-admin/
          curl -v http://localhost:8084/?pagename=ready
          curl -v http://localhost:8084/wp-login.php
          curl -v http://localhost:8084/wp-content/plugins/woocommerce/readme.txt

      - name: Run E2E Tests
        run: npm run test:e2e

      - name: After E2E Tests
        if: always()
        run: npm run docker:down
